export const userAction = {
    START_LOADING: 'START_LOADING',
    END_LOADING: 'END_LOADING',
    LOGIN_SUCCESSFULL: 'LOGIN_SUCCESSFULL',
    LOGOUT: 'LOGOUT',
  }

export const movieAction = {
    START: 'START_POPULAR_MOVIE_REQUEST',
    FINISH: 'FINISH_POPULAR_MOVIE_REQUEST',
    ERROR: 'ERROR_POPULAR_MOVIE_REQUEST',
    START_DETAIL: 'START_DETAIL_MOVIE_REQUEST',
    FINISH_DETAIL: 'FINISH_DETAIL_MOVIE_REQUEST',
    ERROR_DETAIL: 'ERROR_DETAIL_MOVIE_REQUEST',
  }

export const castingAction = {
    START: 'START_CASTING_MOVIE_REQUEST',
    FINISH: 'FINISH_CASTING_MOVIE_REQUEST',
    ERROR: 'ERROR_CASTING_MOVIE_REQUEST',
  }

  export const genreAction = {
    START: 'START_GENRE_REQUEST',
    FINISH: 'FINISH_GENRE_REQUEST',
    ERROR: 'ERROR_GNERE_REQUEST',
    START_GENRE: 'START_GENRE_MOVIE_REQUEST',
    FINISH_GENRE: 'FINISH_GENRE_MOVIE_REQUEST',
    ERROR_GENRE: 'ERROR_GENRE_MOVIE_REQUEST',
  }